production:
  # replace this with a random string of at least 20 characters
  encryption_key: uc4iaH3seirahcohQu1thuheew5huudie8vaezigh5zaecie8n

development:
  encryption_key: 12345

test:
  encryption_key: 12345
